name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Jekyll site with Docker
        run: |
          docker run --rm \
            --user $(id -u):$(id -g) \
            -v ${PWD}:/srv/jekyll \
            -v ${PWD}/_site:/srv/jekyll/_site \
            jekyll/jekyll:latest \
            jekyll build --future --destination /srv/jekyll/_site
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          jekyll_env: production
